export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_PHOTOS_PENDING = 'REQUEST_PHOTOS_PENDING';
export const REQUEST_PHOTOS_SUCCESS = 'REQUEST_PHOTOS_SUCCESS';
export const REQUEST_PHOTOS_FAILED = 'REQUEST_PHOTOS_FAILED';